version: '3'
services:
  api:
    build: ./
    container_name: api
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/usr/src/app/public
    networks:
      - app
    env_file:
      - .env

networks:
  app:
    driver: bridge
